# Generated by Django 4.0.4 on 2022-10-27 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrishopapp', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='Link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
    ]
