# Generated by Django 4.0.4 on 2022-10-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrishopapp', '0003_trending_link_alter_blog_image_alter_trending_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=models.TextField(blank=True),
        ),
    ]
