# Generated by Django 4.0.4 on 2022-10-27 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrishopapp', '0005_newrelease_popular_protein_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='popular',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='popular',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='popular',
            name='title2',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='title3',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='title4',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
