# Generated by Django 4.0.4 on 2022-10-27 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrishopapp', '0006_popular_body2_popular_body3_popular_body4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='Link2',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='Link3',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='Link4',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='popular',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='popular',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
    ]
