# Generated by Django 4.0.4 on 2022-10-27 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrishopapp', '0007_popular_link2_popular_link3_popular_link4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrelease',
            name='Link2',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newrelease',
            name='Link3',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newrelease',
            name='Link4',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newrelease',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newrelease',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newrelease',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newrelease',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='newrelease',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='newrelease',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='newrelease',
            name='title2',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newrelease',
            name='title3',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newrelease',
            name='title4',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
